language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

cache: cargo

before_install:
  # Make sure there's only one josephine crate in the deps directory,
  # which is needed for the rustdoc script.
  - rm -rf target/debug/deps/*josephine*

addons:
  apt:
    sources:
      # Provides newer gcc.
      - ubuntu-toolchain-r-test
    packages:
      - autoconf2.13
      - gcc-5
      - g++-5

env:
  global:
    - CC="gcc-5"
    - CXX="g++-5" 
    # Where to fetch the smup version of mozjs from
    - SMUP_GIT="https://github.com/fitzgen/mozjs"
    - SMUP_BRANCH="smup-smup-smup"
  matrix:
    - CARGO_FLAGS=""
    - CARGO_FLAGS="--release"
    - CARGO_FLAGS="--features debugmozjs"
    - CARGO_FLAGS="--features debugmozjs --release"
    - CARGO_FLAGS="--features smup" SMUP=true
    - CARGO_FLAGS="--features smup --release" SMUP=true

script:
  # If we're doing a smup, patch in the smup repo
  - if [ $SMUP ]; then echo -e "\n[patch.crates-io]\nmozjs = { git = \"$SMUP_GIT\", branch = \"$SMUP_BRANCH\" }" >> Cargo.toml; fi
  - cat Cargo.toml
  - cargo build $CARGO_FLAGS -vv
  - cargo test --doc $CARGO_FLAGS
  # The minidom example currently doesn't work with the smup
  - if [ ! $SMUP ]; then cargo run $CARGO_FLAGS --example minidom; fi
  - cargo run $CARGO_FLAGS --example dbllist
  - if [ -z "$CARGO_FLAGS" ]; then rustdoc -L target/debug/deps/ --test README.md; fi
