language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

script:
  # Make sure there's only one josephine crate in scope
  - rm -rf target/debug/deps/*josephine*
  - cargo build --features debugmozjs -vv
  - cargo test --features debugmozjs
  - cargo run --features debugmozjs --example minidom
  - cargo run --features debugmozjs --example dbllist
  - rustdoc -L target/debug/deps/ --test README.md

cache: cargo
