language: rust
sudo: 9000
dist: xenial
rust:
  - nightly

cache: cargo

before_install:
  # Make sure there's only one josephine crate in the deps directory,
  # which is needed for the rustdoc script.
  - rm -rf target/debug/deps/*josephine*

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf2.13
      - clang
env:
  global:
    - CC="clang"
    - CXX="clang++" 
  matrix:
    - CARGO_FLAGS=""
    - CARGO_FLAGS="--release"
    - CARGO_FLAGS="--features debugmozjs"
    - CARGO_FLAGS="--features debugmozjs --release"
script:
  - cat Cargo.toml
  - cargo build $CARGO_FLAGS -vv
  - cargo test --doc $CARGO_FLAGS
  - cargo run $CARGO_FLAGS --example minidom
  - cargo run $CARGO_FLAGS --example dbllist
  - if [ -z "$CARGO_FLAGS" ]; then rustdoc -L target/debug/deps/ --test README.md; fi
