language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

script:
  - ccache -z
  - CCACHE=$(which ccache) cargo build -vv
  - CCACHE=$(which ccache) cargo test
  - ccache -s

cache:
  - ccache: true
  - directories:
      - $TRAVIS_BUILD_DIR/target
      - $HOME/.cargo
