language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

script:
  # workaround for https://github.com/budziq/rust-skeptic/issues/67
  - rm -rf target/debug/deps/*josephine*
  - ccache -z
  - CCACHE=$(which ccache) cargo build -vv
  - CCACHE=$(which ccache) cargo test
  - CCACHE=$(which ccache) cargo run --example minidom
  - CCACHE=$(which ccache) cargo run --example dbllist
  - ccache -s

cache:
  - ccache: true
  - directories:
      - $TRAVIS_BUILD_DIR/target
      - $HOME/.cargo
