[package]
name = "linjs"
version = "0.0.1"
authors = ["ajeffrey@mozilla.com"]
license = "MPL-2.0"

[lib]

[dependencies]
js = { git = "https://github.com/servo/rust-mozjs" }
libc = "0.2.30"
log = "0.3"

[dev-dependencies]
env_logger = "0.4"
linjs_derive = { path = "linjs-derive" }
