[package]
name = "linjs"
version = "0.0.1"
authors = ["ajeffrey@mozilla.com"]
license = "MPL-2.0"

[lib]

[dependencies]
js = {git = "https://github.com/servo/rust-mozjs"}
log = "0.3"
env_logger = "0.4"
